package main

import (
	"context"
	"encoding/binary"
	"fmt"
	"log"
	"net"
	"net/http"
	"time"

	"connectrpc.com/connect"
	"github.com/cilium/ebpf"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	// Generated by buf
	pb "github.com/tnsr-q/Questions/gen/go/darwinianv1"
	connectpb "github.com/tnsr-q/Questions/gen/go/darwinianv1/darwinianv1connect"

	// Internal observability and swarm bridge
	"github.com/tnsr-q/Questions/internal/obs/metrics"
	"github.com/tnsr-q/Questions/internal/obs/tracing"
	swarmbridge "github.com/tnsr-q/Questions/internal/swarmbridge/client"
)

// UnifiedGateway implements the ConnectRPC interfaces for both planes.
type UnifiedGateway struct {
	routingMap *ebpf.Map
	bridge     *swarmbridge.Client
}

// -----------------------------------------------------------------------------
// 1. THE CONTROL PLANE: eBPF Map Mutations (Called by JAX Swarm)
// -----------------------------------------------------------------------------

// RouteEntry MUST match the C struct in bpf/types/route_entry.h byte-for-byte (24 bytes).
type RouteEntry struct {
	DstIP     uint32   // offset 0
	NextHopIP uint32   // offset 4
	Ifindex   uint32   // offset 8
	DstMAC    [6]byte  // offset 12
	SrcMAC    [6]byte  // offset 18
}

func (g *UnifiedGateway) UpdateAlphaRoute(
	ctx context.Context,
	req *connect.Request[pb.RouteMutation],
) (*connect.Response[pb.RouteAck], error) {
	msg := req.Msg
	obsID := tracing.NewTraceID()

	metrics.EBPFMapMetricsInstance.IncMutationsReceived()

	ack := &pb.RouteAck{
		ObservabilityId: obsID,
		ChecksPassed:    []string{},
		ChecksFailed:    []string{},
	}

	// Dry-run support
	if msg.DryRun {
		metrics.EBPFMapMetricsInstance.IncDryRuns()
		ack.Status = pb.RouteStatus_ROUTE_STATUS_STAGED
		ack.StatusMessage = "Dry-run: mutation validated but not applied"
		ack.ChecksPassed = append(ack.ChecksPassed, "dry_run_validation")
		return connect.NewResponse(ack), nil
	}

	// Validate inputs
	vipKey, err := ipToNetUint32(msg.VirtualIp)
	realIP, err2 := ipToNetUint32(msg.TargetPodIp)
	macAddr, err3 := net.ParseMAC(msg.TargetMacAddress)

	if err != nil || err2 != nil || err3 != nil {
		metrics.EBPFMapMetricsInstance.IncMutationsRejected()
		ack.Status = pb.RouteStatus_ROUTE_STATUS_REJECTED
		ack.StatusMessage = "Admission rejected: Malformed Network Inputs"
		return connect.NewResponse(ack), nil
	}

	// Check TTL expiry
	if msg.TtlMs > 0 {
		proposalAge := time.Now().UnixMilli() - int64(msg.Epoch)
		if proposalAge > int64(msg.TtlMs) {
			metrics.EBPFMapMetricsInstance.IncMutationsRejected()
			ack.Status = pb.RouteStatus_ROUTE_STATUS_REJECTED
			ack.StatusMessage = fmt.Sprintf("Proposal expired: age=%dms > ttl=%dms", proposalAge, msg.TtlMs)
			return connect.NewResponse(ack), nil
		}
	}

	// Build 24-byte RouteEntry matching C struct
	var macBytes [6]byte
	copy(macBytes[:], macAddr)

	entry := RouteEntry{
		DstIP:     realIP,
		NextHopIP: realIP,
		Ifindex:   0,
		DstMAC:    macBytes,
		SrcMAC:    [6]byte{},
	}

	// Atomic Kernel eBPF Map Swap
	if g.routingMap == nil {
		metrics.EBPFMapMetricsInstance.IncMutationsFailed()
		ack.Status = pb.RouteStatus_ROUTE_STATUS_REJECTED
		ack.StatusMessage = "Kernel fault: eBPF map not loaded (not in privileged mode)"
		return connect.NewResponse(ack), nil
	}

	ack.ChecksPassed = append(ack.ChecksPassed, "input_validation", "ttl_check", "map_access")

	if err := g.routingMap.Update(vipKey, entry, ebpf.UpdateAny); err != nil {
		metrics.EBPFMapMetricsInstance.IncMutationsFailed()
		metrics.EBPFMapMetricsInstance.IncMapUpdateErrors()
		ack.Status = pb.RouteStatus_ROUTE_STATUS_PROBE_FAILED
		ack.StatusMessage = fmt.Sprintf("Kernel fault: %v", err)
		ack.ChecksFailed = append(ack.ChecksFailed, "map_update")
		return connect.NewResponse(ack), nil
	}

	metrics.EBPFMapMetricsInstance.IncMutationsApplied()
	ack.Status = pb.RouteStatus_ROUTE_STATUS_APPLIED
	ack.StatusMessage = "eBPF Route Alpha Active"
	ack.AppliedAtUnixNs = time.Now().UnixNano()

	// Report outcome back to swarm (best-effort, non-blocking)
	if g.bridge != nil && msg.MutationId != "" {
		go g.reportOutcome(obsID, msg.VirtualIp, ack)
	}

	return connect.NewResponse(ack), nil
}

// reportOutcome sends the mutation result back to the swarm for GA fitness learning.
func (g *UnifiedGateway) reportOutcome(obsID, vip string, ack *pb.RouteAck) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	statusStr := "APPLIED"
	switch ack.Status {
	case pb.RouteStatus_ROUTE_STATUS_STAGED:
		statusStr = "STAGED"
	case pb.RouteStatus_ROUTE_STATUS_REJECTED:
		statusStr = "REJECTED"
	case pb.RouteStatus_ROUTE_STATUS_PROBE_FAILED:
		statusStr = "PROBE_FAILED"
	case pb.RouteStatus_ROUTE_STATUS_ROLLED_BACK:
		statusStr = "ROLLED_BACK"
	}

	outcome := swarmbridge.ProposalOutcome{
		ProposalID:       obsID,
		VIP:              vip,
		Status:           statusStr,
		ObservedAtUnixMs: time.Now().UnixMilli(),
	}

	if ack.RollbackReason != "" {
		outcome.Rollback = &struct {
			Reason string `json:"reason,omitempty"`
		}{Reason: ack.RollbackReason}
	}

	if _, err := g.bridge.PostOutcome(ctx, outcome); err != nil {
		log.Printf("WARN: failed to report outcome %s: %v", obsID, err)
		metrics.SwarmMetricsInstance.IncOutcomeErrors()
	} else {
		metrics.SwarmMetricsInstance.IncOutcomesReported()
	}
}

// -----------------------------------------------------------------------------
// 2. THE DATA PLANE: Pyodide & ONNX Streaming (Called by Browser JS)
// -----------------------------------------------------------------------------
func (g *UnifiedGateway) StreamSimulation(
	ctx context.Context,
	req *connect.Request[pb.SimRequest],
	stream *connect.ServerStream[pb.CodeChunk],
) error {
	modelID := req.Msg.ModelId
	metrics.GatewayStreamMetrics.IncSessionsStarted()
	defer metrics.GatewayStreamMetrics.DecSessionsActive()

	log.Printf("Frontend requested stream for Alpha model: %s", modelID)

	// Chunk 1: Preamble — safe to run immediately (imports, setup)
	preamble := &pb.CodeChunk{
		Content:    "import numpy as np\nprint('Darwinian Canvas Active.')\n",
		Type:       pb.ChunkType_CHUNK_TYPE_PREAMBLE,
		SequenceId: 1,
	}
	if err := stream.Send(preamble); err != nil {
		metrics.GatewayStreamMetrics.IncSessionsFailed()
		return err
	}
	metrics.GatewayStreamMetrics.AddChunksEmitted(1)
	metrics.GatewayStreamMetrics.AddBytesEmitted(len(preamble.Content))

	// Chunk 2: Execution — triggers Pyodide to run accumulated buffer
	execChunk := &pb.CodeChunk{
		Content:    "\n\n# Alpha cell simulation frame\nrun_sim_frame()\n",
		Type:       pb.ChunkType_CHUNK_TYPE_EXECUTION,
		SequenceId: 2,
	}
	if err := stream.Send(execChunk); err != nil {
		metrics.GatewayStreamMetrics.IncSessionsFailed()
		return err
	}
	metrics.GatewayStreamMetrics.AddChunksEmitted(1)
	metrics.GatewayStreamMetrics.AddBytesEmitted(len(execChunk.Content))

	return nil
}

// -----------------------------------------------------------------------------
// 3. THE BOOTSTRAPPER & HTTP/2 SERVER
// -----------------------------------------------------------------------------
func main() {
	log.Println("Booting Tier 1: Darwinian ConnectRPC Gateway...")

	// 1. Load the pinned eBPF map from the TensorQ pin path.
	const pinPath = "/sys/fs/bpf/tensorq/routing_map"
	m, err := ebpf.LoadPinnedMap(pinPath, nil)
	if err != nil {
		log.Printf("Warning: eBPF map not found at %s, running in mock mode (UpdateAlphaRoute will reject). %v", pinPath, err)
	} else {
		defer m.Close()
		log.Println("eBPF routing_map loaded from pinned path")
	}

	// 2. Initialize swarm bridge client (best-effort — gateway runs without it)
	var bridge *swarmbridge.Client
	if bc, err := swarmbridge.New(swarmbridge.Config{}); err == nil {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		if err := bc.Start(ctx); err != nil {
			log.Printf("Warning: swarm bridge init failed (running without bridge): %v", err)
		} else {
			bridge = bc
			log.Println("Swarm bridge connected — starting background loops")

			// Start telemetry and proposal loops
			cancelLoops, errCh := bridge.StartLoops(
				context.Background(),
				swarmbridge.DefaultLoopConfig(),
				nil,    // telemetryFn — set when we have real metrics to push
				nil,    // proposalHandler — set when mutation-firewalld is wired
			)
			defer cancelLoops()

			// Log loop errors in background
			go func() {
				for e := range errCh {
					log.Printf("swarm bridge loop error: %v", e)
				}
			}()
		}
		cancel()
	} else {
		log.Printf("Warning: swarm bridge client not created (no token file?): %v", err)
	}

	gateway := &UnifiedGateway{routingMap: m, bridge: bridge}

	// 3. Register ConnectRPC Handlers
	mux := http.NewServeMux()
	path, handler := connectpb.NewCortexGatewayHandler(gateway)
	mux.Handle(path, handler)

	// 4. Expose Prometheus metrics
	mux.Handle("/metrics", metrics.DefaultCollector())
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprint(w, "ok")
	})

	// 5. Start h2c server
	address := ":8080"
	log.Printf("Listening for Frontend and Swarm traffic on %s", address)
	log.Printf("Prometheus metrics: http://localhost%s/metrics", address)

	srv := &http.Server{
		Addr:    address,
		Handler: h2c.NewHandler(mux, &http2.Server{}),
	}
	if err := srv.ListenAndServe(); err != nil {
		log.Fatalf("Server crashed: %v", err)
	}
}

// Helper
func ipToNetUint32(ipStr string) (uint32, error) {
	ip := net.ParseIP(ipStr).To4()
	if ip == nil {
		return 0, fmt.Errorf("invalid IPv4")
	}
	return binary.BigEndian.Uint32(ip), nil
}
