// Code generated by bpf2go. DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package objects

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

//go:embed routertc_bpfel.o
var _RouterTCBytes []byte

// RouterTCSpecs contains the eBPF map and program specs parsed from the
// compiled BPF object (little-endian).
type RouterTCSpecs struct {
	MapSpecs struct {
		RoutingMap *ebpf.MapSpec
		StatsMap   *ebpf.MapSpec
	}
	ProgramSpecs struct {
		RoutePackets *ebpf.ProgramSpec
	}
}

// RouterTCSpecs returns the embedded eBPF objects.
func loadRouterTCSpecs() (*RouterTCSpecs, error) {
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(_RouterTCBytes))
	if err != nil {
		return nil, fmt.Errorf("can't load eBPF spec: %w", err)
	}

	specs := &RouterTCSpecs{}
	for name, m := range spec.Maps {
		switch name {
		case "routing_map":
			specs.MapSpecs.RoutingMap = m
		case "stats_map":
			specs.MapSpecs.StatsMap = m
		}
	}
	for name, p := range spec.Programs {
		switch name {
		case "route_packets":
			specs.ProgramSpecs.RoutePackets = p
		}
	}

	return specs, nil
}

// RouterTCMaps contains all eBPF maps after loading.
type RouterTCMaps struct {
	RoutingMap *ebpf.Map `ebpf:"routing_map"`
	StatsMap   *ebpf.Map `ebpf:"stats_map"`
}

// RouterTCPrograms contains all eBPF programs after loading.
type RouterTCPrograms struct {
	RoutePackets *ebpf.Program `ebpf:"route_packets"`
}

// RouterTCObjects contains all loaded eBPF objects (maps + programs).
type RouterTCObjects struct {
	RouterTCMaps
	RouterTCPrograms
}

// LoadRouterTCObjects loads the eBPF collection and populates objs.
// opts may be used to configure map pin paths (see runtime/loader.go).
func LoadRouterTCObjects(objs *RouterTCObjects, opts *ebpf.CollectionOptions) error {
	specs, err := loadRouterTCSpecs()
	if err != nil {
		return err
	}

	var coll *ebpf.Collection
	if opts != nil {
		coll, err = ebpf.NewCollectionWithOptions(specs.toCollectionSpec(), *opts)
	} else {
		coll, err = ebpf.NewCollection(specs.toCollectionSpec())
	}
	if err != nil {
		return fmt.Errorf("can't load eBPF collection: %w", err)
	}

	// Use Assign to populate the struct fields by name.
	if err := coll.Assign(&objs.RouterTCMaps); err != nil {
		coll.Close()
		return fmt.Errorf("can't assign maps: %w", err)
	}
	if err := coll.Assign(&objs.RouterTCPrograms); err != nil {
		coll.Close()
		return fmt.Errorf("can't assign programs: %w", err)
	}

	return nil
}

// toCollectionSpec builds a full ebpf.CollectionSpec from RouterTCSpecs.
func (s *RouterTCSpecs) toCollectionSpec() *ebpf.CollectionSpec {
	cs := &ebpf.CollectionSpec{
		Maps:     make(map[string]*ebpf.MapSpec),
		Programs: make(map[string]*ebpf.ProgramSpec),
	}
	if s.MapSpecs.RoutingMap != nil {
		cs.Maps["routing_map"] = s.MapSpecs.RoutingMap
	}
	if s.MapSpecs.StatsMap != nil {
		cs.Maps["stats_map"] = s.MapSpecs.StatsMap
	}
	if s.ProgramSpecs.RoutePackets != nil {
		cs.Programs["route_packets"] = s.ProgramSpecs.RoutePackets
	}
	return cs
}

// Close releases all references to eBPF objects.
func (o *RouterTCObjects) Close() error {
	var errs []error
	if o.RoutePackets != nil {
		errs = append(errs, o.RoutePackets.Close())
	}
	if o.RoutingMap != nil {
		errs = append(errs, o.RoutingMap.Close())
	}
	if o.StatsMap != nil {
		errs = append(errs, o.StatsMap.Close())
	}
	for i, err := range errs {
		if err != nil {
			return fmt.Errorf("close object %d: %w", i, err)
		}
	}
	return nil
}

// Copy pasters for the runtime/loader.go to use the pinned maps after load.
// These helpers make it easy to unpin and reload.

func (o *RouterTCObjects) UnpinMaps() error {
	var errs []error
	if o.RoutingMap != nil {
		errs = append(errs, o.RoutingMap.Unpin())
	}
	if o.StatsMap != nil {
		errs = append(errs, o.StatsMap.Unpin())
	}
	for i, err := range errs {
		if err != nil {
			return fmt.Errorf("unpin object %d: %w", i, err)
		}
	}
	return nil
}

// Reader for direct byte access to the compiled BPF object.
func RouterTCBytes() io.ReaderAt {
	return bytes.NewReader(_RouterTCBytes)
}
